### ISSUE TITLE
Unexpected T_STRING syntax error

### ISSUE THREAD

**Issue by bigdumbdumb** [uhm-coe/insert-pages#11]
Unexpected T_STRING syntax error with the 3.2.8 & 3.2.9 updates, had to backdate to 3.2.7
Current Wordpress install 4.9.1

Unexpected T_STRING error on line 303 of insert-pages.php

302                 if ( class_exists( '\Elementor\Post_CSS_File' ) ) {
303						$css_file = new \Elementor\Post_CSS_File( $inserted_page->ID );
304						$css_file->enqueue();
305					}

**Comment by figureone** [comment]
You should probably use a PHP version from the last decade ;)
https://wordpress.org/support/topic/insert-pages-parse-error-when-activating-plugin/
