### ISSUE TITLE
A suggestion for a new attribute

### ISSUE THREAD

**Issue by jeffkanazi** [uhm-coe/insert-pages#13]
Hi there,

It would be really nice if you could add a customizable attribute to the wrapper tag. 

I am really going for a mechanism that will allow me to reload specific sections on the screen and a reload attribute in the wrapper div will be very helpful. Ideally, it would be nice to include a reload javascript as well but that can be left to the developer to do outside of the plugin.

I have done some of those changes to my copy of the code but do not want to mess up the master so if someone with a vision on how to best implement this can do it would be fantastic. 

Thanks!

**Comment by figureone** [comment]
You should be able to unset the default `insert_pages_wrap_content` filter and replace with your own:
```
remove_filter( 'insert_pages_wrap_content', array( $insert_pages_plugin, 'insert_pages_wrap_content' ) );
add_filter( 'insert_pages_wrap_content', 'your_wrap_content_filter', 10, 3 );
function your_wrap_content_filter( $content, $posts, $attributes ) {
	// Add whatever custom markup you want here.
	return $content;
}
```

For reference, here's the filter definition:
https://github.com/uhm-coe/insert-pages/blob/master/insert-pages.php#L741-L756

And here's the default filter:
https://github.com/uhm-coe/insert-pages/blob/master/insert-pages.php#L765-L775
