### ISSUE TITLE
readme.txt with Markdown formatting?

### ISSUE THREAD

**Issue by keikoro** [uhm-coe/insert-pages#14]
Hi there, the README doesn't display properly because it's formatted with Markdown but saved as a .txt file. Did this happen by accident or is there a reason for it? (If it were an .md file, it'd be better readable.)

**Comment by figureone** [comment]
Yeah, unfortunately it's WordPress convention:
https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

For other WordPress plugins, I've duplicated the content between readme.txt and README.md, so we can do that here. It's just a little annoying to maintain the duplicate content.
