### ISSUE TITLE
Missing <head> CSS code generated in the child page (Visual Composer)

### ISSUE THREAD

**Issue by Seb33300** [uhm-coe/insert-pages#15]
Hi,

When using your plugin with Visual Composer (this can probably happen using other plugins), we can encounter some rendering issues when specific css code is insered to the child page.

For example, if you add a background on a Visual Composer Row, a css class is added to the row `<div>` and css code is injected into the `<head>` tags of the page.

Unfortunately, the inline css code is not reinjected by your plugin in the parent page, and only the page content is displayed.
Do you think it is a way to catch when some specific css is added on a child page to add it back on the parent page?

How to reproduce with Visual Composer:
![image](https://user-images.githubusercontent.com/915273/45212385-f3495580-b2be-11e8-9d1e-21b8d52bcb50.png)

**Comment by Seb33300** [comment]
Didn't tested yet, but the solution of my issue seems to be given here:
https://stackoverflow.com/questions/48863928/how-to-generate-vc-shortcodes-custom-css-visual-composer

Since it is Visual Composer specific issue, not sure if you will want to fix it or not in your project...
Every theme I have bought on themeforest include Visual Composer so I can imagine it is a very common plugin used by many people.

Maybe a "Visual Composer Content" template choice could be provided by your plugin.

**Comment by Seb33300** [comment]
Looking at your code and it seems that you already handle Visual Composer custom CSS but not working in my case because `if ( defined( 'VCV_VERSION' ) )` is false.
Maybe something changed in newest VC versions.

This works for me:
``` php
echo '<style>'. get_post_meta( $inserted_page->ID, '_wpb_shortcodes_custom_css', true ) . '</style>';
```

**Comment by Seb33300** [comment]
I submitted a pull request, the new constant to check is `WPB_VC_VERSION`

**Comment by figureone** [comment]
Looks OK to me, I'll include it in the next release. Thanks!
