### ISSUE TITLE
Adding an id on the inserted page div

### ISSUE THREAD

**Issue by Seb33300** [uhm-coe/insert-pages#16]
Hello,

Can you provide on option to add an `id` on the `div` element?
In the same way as the class option.

This could be very useful to create anchor link when using your plugin to create One Page website.

Thanks!

**Comment by figureone** [comment]
Sounds like a good idea. The plugin was originally written this way, but changed because IDs should be unique, and someone could insert the same page multiple times. I'll go ahead and add a shortcode param for ID, so you can set one if you like.

**Comment by figureone** [comment]
Added here:
https://github.com/uhm-coe/insert-pages/commit/38c0acb52caf8c498ac42c59d3155a057151047f

This will be included in the next release. Thanks!
