### ISSUE TITLE
It would be great to have a filter for the content before including into the page 

### ISSUE THREAD

**Issue by heiglandreas** [uhm-coe/insert-pages#2]
That way we could f.i. add a featured image of an included page right before the content of that page.

I've already posted this at https://wordpress.org/support/topic/pre-or-postfix-inserted-content?replies=1

**Comment by figureone** [comment]
I'll take a look at the wordpress.org thread and get it included in the plugin. Thanks!

**Comment by figureone** [comment]
Thanks again! This will be included in the next release. Please note that I changed the parameters to the filter:
https://github.com/uhm-coe/insert-pages/commit/a97a2a2cf9c870914abb5c1a3e0328a634197638

**Comment by figureone** [comment]
FYI next version (3.0) includes a change to the insert_pages_wrap_content filter; the second parameter is now a WP_Post object instead of an array of WP_Post objects.
https://github.com/uhm-coe/insert-pages/commit/a9893fa3080c4b10ed9e3647b7780292b20782f4

Let me know if this causes any problems for you.

**Comment by heiglandreas** [comment]
I was already thinking whether there is a case where there might be more than one post in that array ;)

Thanks for pointing out! Is there a due date for the next release? I will fix my code appropriately. 

Just an idea: keep calling the old filter with an array as parameter and introduce a new filter that will be called with the single WP_Post as parameter. That way people will be able to adapt their code successively and when you at a later point remove the "old" filter the old code doesn't get called anymore but nothing breaks codewise due to the changed parameter.

I think that's the way I would introduce this change ;)

**Comment by figureone** [comment]
Thanks for the tips, I should have thought this through better before implementing :)

I think I'm going to proceed with changing the filter and apologize for breaking backwards compatibility. Version 3.0 with the change should be out some time today.

If we see a need for the plugin returning multiple pages in the future, I think I'd like to introduce a filter that modifies the WP_Query lookup (so you can throw more than just a slug or id into the page parameter).

Future changes won't break existing hooks, so I'll definitely be more careful about backwards compatibility.
