### ISSUE TITLE
Many script files appeared

### ISSUE THREAD

**Issue by magsarjav** [uhm-coe/insert-pages#21]
After updating plugin version to 3.5.0, many unknown or useless script files are included in header suddenly. It was fine previous version (3.4..).

**Comment by figureone** [comment]
Version 3.5.1 has been released with a fix that stops loading Gutenberg assets on the front end:
https://github.com/uhm-coe/insert-pages/commit/e4b6df4c50aa44faefa55c703f5004b23956d17f

Also, there is a new Insert Pages setting to disable the Gutenberg block entirely, if you don't intend to use it.

**Comment by magsarjav** [comment]
Thank you for quick response
