### ISSUE TITLE
page settings printed at end of WP page

### ISSUE THREAD

**Issue by slyth86** [uhm-coe/insert-pages#24]
Hi! I see this snippet at the end of the page every time I [insert page]. Looks like plugin conflict. Any inputs in how to fix it would be greatly appreciated. Thanks.

- pm_enable_custom_access: 1
- pm_content_access_group: 3
- neve_meta_enable_content_width: off
- pm_content_access: 2

edit: only happens when display="all"

**Comment by figureone** [comment]
Not a conflict, just use a display other than `all` which includes all post meta (that's what that list is).
Plenty of discussion in the forums on this if you need more details:
https://wordpress.org/support/topic/issue-when-inserting-custom-post-type/
