### ISSUE TITLE
Adding shortcode in function.php hook

### ISSUE THREAD

**Issue by phantomodm** [uhm-coe/insert-pages#26]
Hello,

Thank you for this plugin.. I want to add the shortcode in a function.php function.. I've tried the do_shortcode() code and it simply does not execute. Is this plugin designed to work this way? 

Thanks.
A

**Comment by figureone** [comment]
It is; what hook are you running in? It's possible you are trying to do it before `plugins_loaded`.
https://developer.wordpress.org/reference/hooks/plugins_loaded/

**Comment by phantomodm** [comment]
Hi Paul, Thanks for responding.  I’ve added it during a hook in the normal loading of the page. So I’m using woocommerce.  I want it to fire off on a product page before the woocommerce_before_product_summary hook. -A---- On Thu, 22 Oct 2020 17:15:31 -0400  notifications@github.com<notifications@github.com> wrote ---- 
It is; what hook are you running in? It's possible you are trying to do it before plugins_loaded. 
https://developer.wordpress.org/reference/hooks/plugins_loaded/

**Comment by figureone** [comment]
Maybe you're not echoing the content out to the browser? Might look something like `echo do_shortcode( ... );`

**Comment by phantomodm** [comment]
Thanks for you help Paul.. I finally got it.. Thanks for the quick support.. 






---- On Thu, 22 Oct 2020 17:39:36 -0400 Paul Ryan <notifications@github.com> wrote ----




Maybe you're not echoing the content out to the browser? Might look something like echo do_shortcode( ... );
