### ISSUE TITLE
WordPress V5.7 JQuery

### ISSUE THREAD

**Issue by myob9a** [uhm-coe/insert-pages#27]
WordPress V5.7 is changing jQuery versions with consequences as there is no backward compatibility.  jquery Migrate Helper tells me that Insert Pages, which I use a lot, will have a problem.  Is this under review?

/wp-content/plugins/insert-pages/js/wpinsertpages.js
/wp-content/plugins/insert-pages/js/wpinsertpages.js
/wp-content/plugins/insert-pages/js/wpinsertpages.js 
/wp-content/plugins/insert-pages/js/wpinsertpages.js
/wp-content/plugins/insert-pages/js/wpinsertpages.js

**Comment by figureone** [comment]
It is now! :)
We'll take a look and try to get an update out before 5.7 hits in March.

**Comment by figureone** [comment]
Fixed in https://github.com/uhm-coe/insert-pages/commit/c7891de6d365b1159402a2a4844241a8e3ada902

Please test under WordPress 5.7 to confirm the deprecation notices are gone.
