### ISSUE TITLE
Insert Pages-Editor-Dialog breaks Frontend-Tinymce

### ISSUE THREAD

**Issue by purivus-dev** [uhm-coe/insert-pages#28]
https://github.com/uhm-coe/insert-pages/blob/2f30c70629e74332b8d7ded0549dc8bb48d78367/insert-pages.php#L1153-L1161
Function `page_template_dropdown` exists in front-end too and thus the continuing execution of the wrapping function `insert_pages_wp_tinymce_dialog()` in front-end breaks my front-end-`wp_editor()`.
I fixed the bug (after hours of detective work) by removing the action `insert_pages_wp_tinymce_dialog` from the hook `before_wp_tiny_mce`.
Generally I'd propose to use the switch `!is_admin()` to prevent execution in frontend.
As for your plugin itself, I'm using it successfully, thanks.

**Comment by figureone** [comment]
We're actually working on refactoring this, coming out of this discussion:
https://wordpress.org/support/topic/insert-page-not-visibile-in-plugins/

`page_template_dropdown()` should only be defined in `wp-admin` context; but you may have another plugin including it on the frontend. We found that we can accomplish what's needed by relying on `WP_Theme` methods that are consistently available on the frontend.

Will let you know when the next version is released with the fix.

**Comment by figureone** [comment]
Oh, one other comment: the other poster specifically requested the Insert Pages TinyMCE toolbar button be available on the frontend. It sounds like you prefer not to have it (perhaps because of security issues since it allows users to browse all site content?). Would you like an options toggle to enable/disable it on frontend `wp_editor()` calls?

**Comment by figureone** [comment]
Aloha, version 3.6.0 is out with modifications to loading on the front end. By default, the Insert Pages TinyMCE widget will not try to load outside of the wp-admin context (its initialization happens in `admin_head`).

However, if you want it to load on the frontend, you just need to hook that initialization into normal `wp_head`, for example:
```
if ( class_exists( 'InsertPagesPlugin' ) ) {
	add_filter( 'wp_head', array( InsertPagesPlugin::get_instance(), 'insert_pages_admin_init' ) );
}
```
