### ISSUE TITLE
A couple of Problems

### ISSUE THREAD

**Issue by paradisepools** [uhm-coe/insert-pages#29]
Love the plug in just having a couple of minor issues that I can work around

1. The insert button is off screen and I can not scroll down to it. I have to minimize the page to get to it
2. Adding a page to my post is freezing the scroll of my WP page . I can edit what I can see, but can't move the screen. have to refresh  to get it to come back

thats it, great product otherwise

**Comment by figureone** [comment]
Can you describe the specific context you're seeing these issues, and what other plugins you are using to modify the vanilla WordPress experience? 

Insert Pages works in a bunch of different contexts (e.g., Classic Editor toolbar button; shortcode; widget; Gutenberg block), and it's hard to tell from your description what you're seeing.

**Comment by figureone** [comment]
Checking in again on this before closing, let us know if you can describe the issues in more detail.
