### ISSUE TITLE
Embed page exceeds content width in mobile

### ISSUE THREAD

**Issue by rafamerino** [uhm-coe/insert-pages#30]
Hi,

I'm using your plugin in combination with "Tabs" block from "[Ultimate Addons for Gutenber](https://es.wordpress.org/plugins/ultimate-addons-for-gutenberg/)"

When a post/page is loaded from mobile view inside a tab block, embed content doesn’t respect the content width from the superior block (tabs). I’ve tried also to insert the block inside a Gutenberg “container” block (from [Stackable blocks](https://es.wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/)) to play with settings trying to set a max width for the inside blocks (tabs and yours), but nope, still the problem.

Image with the problem: https://i.imgur.com/qB3mUMW.png (Tab with content embedded using your plugin)
How should look: https://i.imgur.com/IcK0Odi.png (Tab with real content, no embedded)

Any way to fix this or to set a max-width parameter for an inserted content?

**Comment by figureone** [comment]
Insert Pages doesn't add any styling for inserted elements, so you'll have to add those styles yourself. Odd that whatever theme you're using doesn't do it already! All inserted pages include the `insert-page` class so you can target them in your own style rules.

You can also try switching the wrapper element from `div` to `span` in the plugin settings; that might be a quick workaround, but it all depends on whatever styles your theme is applying.
