### ISSUE TITLE
Page in theme nav bar not working in 3.7.0

### ISSUE THREAD

**Issue by benavent** [uhm-coe/insert-pages#31]
Our site uses Insert Pages to inset a navigation bar at the top of each page.

The shortcode is [insert page='nav-bar-template' display='content'].

We are using this in the "Sitewide after Header Shortcode" setting of the Kadence Virtue Theme.

It was working on 3.6.1, but not on 3.7.0.

Help!

**Comment by figureone** [comment]
There was a security update in the latest version to prevent unprivileged users (e.g., Contributors or Authors) from inserting Private pages belonging to other users. Does that match your scenario?

**Comment by figureone** [comment]
Checking in again on this before closing, let us know if you are still seeing an issue.

**Comment by figureone** [comment]
Closing comment, try switching to the "normal" insert method instead of "legacy" in Insert Pages settings, that may work for you.
