### ISSUE TITLE
Wrong page inserted

### ISSUE THREAD

**Issue by oliviergenest** [uhm-coe/insert-pages#32]
Everything was working well, however since update to version 5.8.2 of Wordpress the inserted page is not the right one.
E.g. in the page `https://www.trialog.com/fr/evenements-2/` my code is :
`[insert page='eventtable' display='content']`
However, the inserted content is the one of this page `https://www.trialog.com/fr/nouvelle-offre-de-formation-pour-les-compteurs-intelligents/` instead of `https://www.trialog.com/en/eventtable/`
I have tried to use the id of the page (6657) instead of its name (eventtable) but the issue remains the same.
Any idea of what is happening? 
Thanks for your help.

**Comment by figureone** [comment]
Strange...can you try going to Dashboard > Settings > Insert Pages and change the `Insert method` to the other option?

**Comment by oliviergenest** [comment]
Thank you! It was on "Legacy mode" but now it works fine on "Normal mode".

**Comment by oliviergenest** [comment]
Issue fixed by setting "Insert method" to "Normal mode"
