### ISSUE TITLE
Some kind of conflict with page editing options

### ISSUE THREAD

**Issue by StefanPeev** [uhm-coe/insert-pages#37]
The plugin causes some kind of conflict with:

WordPress version 5.9.3
Current theme: Storefront (version 4.1.0)
Current plugin: WooCommerce (version 6.5.0)
PHP version 7.3.33

When plugin is activated I can't edit product page in WooCommerce. If the plugin is deactivated the product page can be normally edited.

Error Details
=============
An error of type E_ERROR was caused in line 20 of the file /home/localfonts/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php. Error message: Uncaught Error: Call to a member function get_type() on bool in /home/localfonts/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php:20
Stack trace:
#0 /home/localfonts/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include()
#1 /home/localfonts/public_html/wp-admin/includes/template.php(1395): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array)
#2 /home/localfonts/public_html/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#3 /home/localfonts/public_html/wp-admin/post.php(206): require('/home/localfont...')
#4 {main}
  thrown

**Comment by figureone** [comment]
Try switching to the "normal" insert method instead of "legacy" in Insert Pages settings. More details here:
https://wordpress.org/support/topic/conflict-with-facebook-for-woocommerce-2/#post-15290729
