### ISSUE TITLE
ReferenceError: Can't find variable: QTags

### ISSUE THREAD

**Issue by Steveorevo** [uhm-coe/insert-pages#38]
Currently experiencing this issue with WordPress 6.0. Deactivating the plugin resolves the issue.

**Comment by figureone** [comment]
Sounds like a dependency on the Classic Editor plugin, assuming you don't have that installed?
We can check for its existence before adding the quicktag toolbar button for Insert Pages.

**Comment by figureone** [comment]
Ref: https://perishablepress.com/wordpress-fix-error-qtags-not-defined/
