### ISSUE TITLE
v3.0.1 problem

### ISSUE THREAD

**Issue by jcbenton** [uhm-coe/insert-pages#4]
Paul,

First, great plugin. It is really useful. Second, v3.0.1 broke the internets. I was using it in the excerpt field in Easy Digital Downloads, which worked great until I updated Insert Pages. The desired content is still displayed, but now other parts of EDD get broken. 

Sorry I don't have more than that.

**Comment by jcbenton** [comment]
I am going to try and debug some of this today.

**Comment by jcbenton** [comment]
This function: insertPages_trim_excerpt

causes some serious problems if you use [insert_pages] in the excerpt field of a page.

**Comment by jcbenton** [comment]
And then I checked the radio button to use the normal method for inserts and the problem went away. I guess it was defaulted to legacy? anyway ...

**Comment by figureone** [comment]
Odd, I would have expected the "legacy" method to function better; insertPages_trim_excerpt() only gets used in the "normal" method. Regardless, I'll try to find some time to test against Easy Digital Downloads. Thanks for the report!
