### ISSUE TITLE
WordPress update 6.3.2

### ISSUE THREAD

**Issue by FrankySonOfOdin** [uhm-coe/insert-pages#53]
I just updated to WordPress 6.3.2 and now i'm getting an error in the editor. "Error loading block: invalid parameter(s): attributes"

I have disabled this extension. All other extensions appear to work fine. When I re-enable it the error returns.

The plugin page includes the warning "Warning: This plugin has not been tested with your current version of WordPress."

**Comment by figureone** [comment]
We tested on WordPress 6.3.2 on twentyseventeen and twentytwentythree themes and had no issue with the Insert Pages block. Can  you provide more details about what theme and plugins you are running, and also try testing whether it works on any of the core themes?

**Comment by FrankySonOfOdin** [comment]
I have confirmed that I have the same issue, but with a twist.

For grimms I published the page where I'm encountering the error, and It builds the front end page despite the warnings in the editor.
> I'm using the Gutenberg editor.

So there's at least a workaround, and perhaps this has less to do with your plugin (which I love btw) and more to do with the editor. I'll be wrapping my brain around this one for a tick. If something stands out I'd be happy to test it.

---
Since the error in the editor specifies attributes, here's my configuration.
- Page URL points to a local domain address.
- Display: Content
- Post Thumbnail Size: Thumbnail
- Custom CSS Class: [blank]
- Custom Element ID: [blank]
- Custom Querystring: [blank]
- Inline? F
- Reveal Private Pages? F

No additional "Advanced" CSS Classes

---

- I tested with the Twenty twenty-three theme, and encountered the same error in the editor, but this is where I learned that it's still presenting on the front-end.
- My current Theme is Podcaster Secondline https://wordpress.org/themes/podcaster-secondline/
- I have more plugins for QOL in WP than what I do for page formatting.
  - Otter Page Builder Blocks & Extensions for Gutenberg https://wordpress.org/plugins/otter-blocks/
  - Syntax Highlighter https://wordpress.org/plugins/syntaxhighlighter/
- Just in case my expectation is unreasonable here are my other active plugins
  - Anchor Episodes Index https://wordpress.org/plugins/anchor-episodes-index/
  - Envira Gallery Lite https://wordpress.org/plugins/envira-gallery-lite/
  - Media Library Organizer https://wordpress.org/plugins/media-library-organizer/
  - The Hostgator Plugin (oddly with no wordpress.org page. the link leads to the HG URL)
  - Wicked Folders https://wordpress.org/plugins/wicked-folders/

**Comment by figureone** [comment]
So strange. It must be a conflict with one of your other plugins. Can you follow the instructions here and see if you can narrow down which one it is?
https://wordpress.org/support/topic/products-by-category-error-loading-block-invalid-parameters-attributes/#post-14844087

Basically just deactivate the other plugins one at a time and see if the error message in the editor goes away. We tested all of the plugins your listed (except for the Hostgator one) and still didn't get the error message, so I'm not sure what's up.

Lastly I guess just confirm that "Settings > Insert Pages" in the WordPress dashboard has "Gutenberg block" enabled and "Insert method" set to normal.

**Comment by FrankySonOfOdin** [comment]
Okay. Just in case it wasn't strange enough.

It looks like the act of restarting the addons did the job.

Thank you for your time.
