### ISSUE TITLE
Insert page with content='all' displays footnotes when there are none

### ISSUE THREAD

**Issue by dregad** [uhm-coe/insert-pages#54]
## Context

I am using the following shortcode to insert in a page, another one that is also available as a standalone page:

```
[insert page='xxx' display='all']
```

Note: I'm using `display='all'` because I want to have both the title and the full contents.

## Problem

This used to work just fine, but I recently noticed that at the bottom of the included page, there is a new *footnotes* section displayed even though as far as I know there are no footnotes in the included page. 

![image](https://github.com/uhm-coe/insert-pages/assets/449891/51c1c337-0263-48e8-8419-1adef350dbc6)

Generated HTML
```html
<div data-post-id="3704" class="insert-page insert-page-3704 "><h1 class="insert-page-title">
    <!-- SNIP included page's contents -->
<ul class="post-meta">
<li><span class="post-meta-key">footnotes&nbsp;:</span> </li>
</ul>
</div>
```

I'm not sure when the problem actually started occurring, but quite possibly a few weeks ago when I upgraded to WP 6.3, which introduced [footnotes](https://wordpress.org/documentation/wordpress-version/version-6-3/#annotate-with-the-footnotes-block).

## Expected behavior

The *footnotes* bullet should not be shown, when there are no actual footnotes in the included document.

Moreover, the `footnotes` text is in English, while the WP instance's site language is French; I think this should be translated.

## Workaround

Insert 2 shortcodes, one with _title_, and one with _contents_.

**Comment by figureone** [comment]
We are considering just changing the `all` display to be title+content. I'm not aware of anyone in the wild using the postmeta display, and like you noticed, the block editor is increasingly using postmeta to store data like footnotes. 

`all` has been in the plugin since version 1, and was really just a tech demo to show it could fetch related postmeta and show it in an unordered list underneath the post content.

Let us know if you have thoughts on that!

**Comment by dregad** [comment]
> changing the all display to be title+content

That would work for me just as well as my initial suggestion. Maybe less explicit as to what it does, but has the advantage of backwards compatibility. 

Looking forward for a fix, whichever you choose to implement.

**Comment by figureone** [comment]
Resolved in https://github.com/uhm-coe/insert-pages/issues/55
