### ISSUE TITLE
Add option "title + content" to display setting

### ISSUE THREAD

**Issue by dregad** [uhm-coe/insert-pages#55]
I frequently have to include a whole page including its title; I used to use `display='all'` but this is now causing a problem (see #54)

It would be nice to have an option to display both *title* and *content* in a single shortcode, instead of having to insert 2 of them.

**Comment by figureone** [comment]
Sorry for the delay on this one; `display='title-content'` will be available in the next version due out shortly!
https://github.com/uhm-coe/insert-pages/commit/be03973f471898d8d8eb8c1c1b5b6582653bfedd

**Comment by dregad** [comment]
Awesome, thank you ! 😃

**Comment by dregad** [comment]
I updated the site and tested the new _title + content_ option, it works perfectly ! Thanks a lot.
