### ISSUE TITLE
Insert post/page with already inserted isn't possible!

### ISSUE THREAD

**Issue by redpmorg** [uhm-coe/insert-pages#8]
It would be great if it could:
Post1, Post2
PageA  [insert post1] [insert post2] //works
PageB [insert PageA] //insert only elements defined in PageA except inserted elements

**Comment by figureone** [comment]
Sure, that's just a safety feature to prevent infinite loops (page A in page B, page B also in A).
Disable it by hooking into the following in your theme:
https://github.com/uhm-coe/insert-pages/blob/master/readme.txt#L227-L232

**Comment by redpmorg** [comment]
Nice, thank you!
